<?php

class ProductTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		//DB::table('products')->truncate();

		$products = array(
            array(
                'owner_id' => 10222,
                'product_title' => 'product 1 102222',
                'product_description' => 'Desc',
                'product_price' => 1200,
                'product_category' => 'cat1',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10000,
                'product_title' => 'product 1 10-0000',
                'product_description' => 'Desc',
                'product_price' => 1200,
                'product_category' => 'cat1',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10233,
                'product_title' => 'product 1 10233',
                'product_description' => 'Desc',
                'product_price' => 1200,
                'product_category' => 'cat1',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Adult Membership',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Junior Membership',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Season Ticket (Adult)',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Season Ticket (Junior)',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Community Shares',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'TreasureLine',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Holiday Draw',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => '127 Club',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Match Sponsor',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Matchball Sponsor',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Matchday Programme Sponsor',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Programme Adverts',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Pitchside Hording',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Pink Sponsorship',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Newsletter Sponsor',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Community Sponsor',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Youth Team Sponsor',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Women Team Sponsor',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Player Sponsor',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Club Donations',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'DF Donations',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Club Events',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Merchanidise',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),
            array(
                'owner_id' => 10222,
                'product_title' => 'Away Match Travel',
                'product_description' => '',
                'product_price' => 1000,
                'product_category' => '',
                'created_at' => DB::raw('CURRENT_TIMESTAMP'),
                'updated_at' => DB::raw('CURRENT_TIMESTAMP'),
            ),

    	);

		// Uncomment the below to run the seeder
		DB::table('products')->insert($products);
	}

}
